language: node_js
node_js:
- "8"
dist: trusty
sudo: required

os:
- linux
addons:
  apt:
    update: true
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

jobs:
  include:
  - stage: lint
    script:
    - ng lint
  - stage: build & publish showcase
    script:
    - npm run build:demo
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GH_TOKEN
      local_dir: dist/ng-eventstore-listing-showcase
    if: branch = master
  - stage: build & publish lib
    script:
    - npm run build:lib
    - npm run publish:lib
    if: branch = master
