version: '3'

services:
  dbserver:
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventstore
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
